# Generated by Django 5.2.15 on 2026-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_activity_code_activity_description_subactivity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
