# Generated by Django 5.1.4 on 2026-06-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_activity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactivity',
            name='assigned_to',
        ),
    ]
