# Generated by Django 5.1.4 on 2026-06-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='time_spent_minutes',
        ),
    ]
